env:
  browser: true
  jquery: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 5
  sourceType: script
  jsx: false
rules:
  comma-dangle:
    - error
    - "never"
  max-len:
    - error
    - {code: 120, tabWidth: 2, ignoreTrailingComments: true}
  no-plusplus:
    - error
    - {allowForLoopAfterthoughts: true}
  no-var: off
  object-shorthand: off
  prefer-arrow-callback: off
  prefer-const: off
  prefer-destructuring: off
  prefer-numeric-literals: off
  prefer-rest-params: off
  prefer-spread: off
  prefer-template: off
  strict:
    - error
    - "global"
  vars-on-top: off
